src/AspNetCore/Components/CartSummaryViewComponent.cs
using AspNetCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace SportsStore.Components {

    public class CartSummaryViewComponent : ViewComponent {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService) {
            cart = cartService;
        }

        public IViewComponentResult Invoke() {
            return View(cart);
        }
    }
}

src/AspNetCore/Components/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCore.Components
{
    public class LoginViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/AspNetCore/Components/MenuViewComponent.cs
using AspNetCore.Infrastructure;
using AspNetCore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCore.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private ICatRepository repo;

        public MenuViewComponent(ICatRepository repo)
        {
            this.repo = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.cartNumber = GetCart().Lines.Count();
            return View(repo.Cats);
        }
        private Cart GetCart()
        {
            Cart cart = HttpContext.Session.GetJson<Cart>("Cart") ?? new Cart();
            return cart;
        }
    }
}

src/AspNetCore/Components/OrderDetailViewComponent.cs
using AspNetCore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCore.Components
{
    public class OrderDetailViewComponent : ViewComponent
    {
        private IOrderRepository repository;
        public OrderDetailViewComponent(IOrderRepository repository)
        {
            this.repository = repository;
        }
        public IViewComponentResult Invoke(int id)
        {
            return View(repository.GetOrderDetailById(id));
        }
    }
}

src/AspNetCore/Components/SignupViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCore.Components
{
    public class SignupViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/AspNetCore/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCore.Models;
using Microsoft.AspNetCore.Http;
using AspNetCore.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace AspNetCore.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IProductRepository productRepo;
        private IOrderRepository orderRepo;
        private IHostingEnvironment _environment;
        private ICatRepository catRepo;
        public int pageSize = 5;

        public AdminController(IProductRepository productRepo, IHostingEnvironment environment, IOrderRepository orderRepo,
            ICatRepository catRepo)
        {
            this.productRepo = productRepo;
            this.orderRepo = orderRepo;
            this.catRepo = catRepo;
            _environment = environment;
        }
        // GET: /<controller>/
        [AllowAnonymous]
        public IActionResult Index(int page = 1)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("admin"))
                {
                    return View(productRepo.GetPage(pageSize, page));
                }
                else
                {
                    TempData["Message"] = new[] { "danger", "Tài khoản không có quyền quản trị" };
                    return Redirect("/");
                }
            }
            else
            {
                return Redirect("/");
            }
        }
        public IActionResult Product(int id)
        {
            ViewBag.Cat = catRepo.Cats;
            return View(new ProductFormViewModel
            {
                product = productRepo.GetById(id)
            });
        }
        [HttpPost]
        public async Task<IActionResult> Product(ProductFormViewModel model)
        {
            if(model.img != null)
            {
                var uploads = Path.Combine(_environment.WebRootPath, "images");
                using (var fileStream = new FileStream(Path.Combine(uploads, model.img.FileName), FileMode.Create))
                {
                    await model.img.CopyToAsync(fileStream);
                }
                model.product.Image = $"images/{model.img.FileName}";
            }
            if(productRepo.SaveProduct(model.product))
            {
                TempData["Message"] = new[] { "success", "Đã lưu sản phẩm" };
                return View("Index", productRepo.GetPage(pageSize, 1));
            }
            else
            {
                TempData["Message"] = new[] { "danger", "Lỗi lưu sản phẩm" };
                return View(model);
            }
        }
        public ViewResult CreateProduct()
        {
            ViewBag.Cat = catRepo.Cats;
            return View("Product", new ProductFormViewModel());
        }
        public IActionResult DeleteProduct(int id)
        {
            if(productRepo.Delete(id))
            {
                TempData["Message"] = new[] {"success", "Đã xóa sản phẩm" };
                return View("Index", productRepo.GetPage(pageSize, 1));
            }
            else
            {
                TempData["Message"] = new[] {"danger", "Lỗi xóa sản phẩm" };
                return View("Index", productRepo.GetPage(pageSize, 1));
            }
        }
        public IActionResult Order(int page = 1)
        {
            return View(orderRepo.GetOrder(10, page));
        }
        public IActionResult ChangeOrder(int id, bool shipped)
        {
            if(orderRepo.SaveOrder(id,shipped))
            {
                TempData["Message"] = new[] { "success", "Cập nhật đơn hàng thành công" };
            }
            else
            {
                TempData["Message"] = new[] { "danger", "Cập nhật đơn hàng thất bại" };
            }
            return View("Order", orderRepo.GetOrder(10, 1));
        }
        public IActionResult DeleteOrder(int id)
        {
            if (orderRepo.DeleteOrder(id))
            {
                TempData["Message"] = new[] { "success", "Xóa đơn hàng thành công" };
            }
            else
            {
                TempData["Message"] = new[] { "danger", "Xóa đơn hàng thất bại" };
            }
            return View("Order", orderRepo.GetOrder(10, 1));
        }
    }
}

src/AspNetCore/Views/Shared/Components/Menu/Default.cshtml
@model IEnumerable<Cat>

<header class="c-layout-header c-layout-header-2 c-layout-header-dark-mobile c-header-transparent-dark" data-minimize-offset="80">
    <div class="c-navbar">
        <div class="container">
            <!-- BEGIN: BRAND -->
            <div class="c-navbar-wrapper clearfix">
                <div class="c-brand c-pull-left">
                    <a href="~/" class="c-logo">
                        <img src="~/images/logo-1.png" alt="Shop" class="c-desktop-logo">
                        <img src="~/images/logo-1.png" alt="Shop" class="c-desktop-logo-inverse">
                        <img src="~/images/logo-1.png" alt="Shop" class="c-mobile-logo">
                    </a>
                    <button class="c-hor-nav-toggler" type="button" data-target=".c-mega-menu">
                        <span class="c-line"></span>
                        <span class="c-line"></span>
                        <span class="c-line"></span>
                    </button>
                    <button class="c-topbar-toggler" type="button">
                        <i class="fa fa-ellipsis-v"></i>
                    </button>
                    <button class="c-search-toggler" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                    <button class="c-cart-toggler" type="button">
                        <i class="icon-handbag"></i>
                        <span id="cartNumber2" class="c-cart-number c-theme-bg"></span>
                    </button>
                </div>
                <!-- END: BRAND -->
                <!-- BEGIN: QUICK SEARCH -->
                <form class="c-quick-search" asp-action="Search" asp-controller="Home" asp-route-page="1">
                    <input type="text" name="search" placeholder="Nhập tên sách cần tìm..." value="" class="form-control" autocomplete="off">
                    <span class="c-theme-link">&times;</span>
                </form>
                <!-- END: QUICK SEARCH -->
                <!-- BEGIN: HOR NAV -->
                <!-- BEGIN: LAYOUT/HEADERS/MEGA-MENU -->
                <!-- BEGIN: MEGA MENU -->
                <!-- Dropdown menu toggle on mobile: c-toggler class can be applied to the link arrow or link itself depending on toggle mode -->
                <nav class="c-mega-menu c-pull-right c-mega-menu-dark c-mega-menu-dark-mobile c-theme c-fonts-uppercase c-fonts-bold">
                    <ul class="nav navbar-nav c-theme-nav">
                        <li>
                            <a href="~/" class="c-active c-link">
                                Trang chủ
                                <span class="c-arrow c-toggler"></span>
                            </a>
                        </li>
                        <li class="c-menu-type-classic">
                            <a asp-action="List" asp-controller="Home" asp-route-page="1" asp-route-id="" class="c-link dropdown-toggle">
                                Loại sách
                                <span class="c-arrow c-toggler"></span>
                            </a>
                            <ul class="dropdown-menu c-menu-type-classic c-pull-left">
                                @foreach (Cat item in Model)
                                {
                                    <li class="dropdown-submenu">
                                        <a asp-action="List" asp-controller="Home" asp-route-id="@item.Id" asp-route-page="1">
                                            @item.Name
                                            <span class="c-arrow c-toggler"></span>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </li>
                        <li class="c-search-toggler-wrapper">
                            <a href="#" class="c-btn-icon c-search-toggler">
                                <i class="fa fa-search"></i>
                            </a>
                        </li>
                        <li class="c-cart-toggler-wrapper">
                            <a asp-action="Index" asp-controller="Cart" class="c-btn-icon c-cart-toggler">
                                <i class="icon-handbag c-cart-icon"></i>
                                <span id="cartNumber" class="c-cart-number c-theme-bg">@ViewBag.cartNumber</span>
                            </a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a asp-action="Index" asp-controller="Account" asp-route-page="1" class="c-btn-border-opacity-04 c-btn btn-no-focus c-btn-header btn btn-sm c-btn-border-1x c-btn-white c-btn-circle c-btn-uppercase c-btn-sbold">
                                    <i class="icon-user"></i> Tài khoản
                                </a>
                            </li>
                            <li>
                                <a asp-action="Logout" asp-controller="Account" asp-route-returnUrl="@Url.RouteUrl(ViewContext.RouteData.Values)" class="c-btn-border-opacity-04 c-btn btn-no-focus c-btn-header btn btn-sm c-btn-border-1x c-btn-white c-btn-circle c-btn-uppercase c-btn-sbold">
                                    Đăng xuất
                                </a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a href="javascript:;" data-toggle="modal" data-target="#login-form" class="c-btn-border-opacity-04 c-btn btn-no-focus c-btn-header btn btn-sm c-btn-border-1x c-btn-white c-btn-circle c-btn-uppercase c-btn-sbold">
                                    <i class="icon-user"></i> Đăng nhập
                                </a>
                            </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li>
                                <a asp-action="Index" asp-controller="Admin" asp-route-page="1" class="c-btn-border-opacity-04 c-btn btn-no-focus c-btn-header btn btn-sm c-btn-border-1x c-btn-white c-btn-circle c-btn-uppercase c-btn-sbold">
                                    Quản trị
                                </a>
                            </li>
                        }
                    </ul>
                </nav>
                <!-- END: MEGA MENU -->
                <!-- END: LAYOUT/HEADERS/MEGA-MENU -->
                <!-- END: HOR NAV -->
            </div>
            <!-- BEGIN: LAYOUT/HEADERS/QUICK-CART -->
            <!-- BEGIN: CART MENU -->
            @await Component.InvokeAsync("CartSummary")
            <!-- END: CART MENU -->
            <!-- END: LAYOUT/HEADERS/QUICK-CART -->
        </div>
    </div>
</header>